---
- block:

    - name: "Ensure existense of /tmp/victoria-metrics-v{{ victoriametrics_version }}"
      ansible.builtin.file:
        path: "/tmp/victoria-metrics-v{{ victoriametrics_version }}"
        state: directory

    - name: Unarchive victoriametrics binaries
      become: false
      unarchive:
        src: "{{ victoriametrics_repo_dir }}/victoria-metrics-amd64-v{{ victoriametrics_version }}.tar.gz"
        dest: "/tmp/victoria-metrics-v{{ victoriametrics_version }}"
        creates: "/tmp/victoria-metrics-v{{ victoriametrics_version }}/victoria-metrics-prod"
      check_mode: false

    - name: "Copy victoriametrics to {{ victoriametrics_install_dir }}"
      ansible.builtin.copy:
        src: "/tmp/victoria-metrics-v{{ victoriametrics_version }}/victoria-metrics-prod"
        dest: "{{ victoriametrics_install_dir }}/victoriametrics"
        owner: "{{ victoriametrics_system_user }}"
        group: "{{ victoriametrics_system_group }}"
        mode: 0755
        remote_src: yes
      notify: restart vm

- name: "Create victoriametrics data directory {{ victoriametrics_storage_data_path }}"
  file:
    path: "{{ victoriametrics_storage_data_path }}"
    state: directory
    owner: "{{ victoriametrics_system_user }}"
    group: "{{ victoriametrics_system_group }}"
    mode: 0755
